import type { NextPage } from "next";
import Head from "next/head";
import Nav from "../components/Navbar";
import Showcase from "../components/Showcase";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Nav />
        <Showcase />
      </div>
    </>
  );
};

export default Home;
